config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'venues#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :venues, only: [ :index, :show, :update]
  resources :bookings, except: [ :destroy ] do
    collection do
      get 'latest'
    end

    member do
      get 'fetch_status'
    end
  end

  get ':token', to: "bookings#show", token: /[A-Z]\d{5}/
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :venue

  before_validation :assign_random_venue, on: :create

  after_validation :token_gen, on: :create

  validates :date, presence: true
  validates :time, presence: true
  validates :status, presence: true

  after_save :call_uber, on: :create

  attr_accessor :venue_types

  private

  def assign_random_venue
    @venue_types = ['restaurant', 'bar', 'nightclub'] if @venue_types[1].blank?

    self.venue = Venue.find_random(@venue_types.reject(&:blank?))
    self.time = Time.now
    self.date = Date.today
  end

  def call_uber
    # TODO asynchronously call Uber API
  end

  def token_gen
    # Generate a random lowercase letter
    letter = (0...1).map { ('A'..'Z').to_a[rand(26)] }.join
    # GENERATE 5 random numbers in a string
    numbers = (0...5).map { (0..9).to_a[rand(5)] }.join
    # COMBINED TOKEN
    token = letter + numbers
    self.token = token
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [ :edit, :update, :fetch_status]

  skip_before_action :verify_authenticity_token, only: :fetch_status
  skip_before_action :authenticate_user!, if: -> { params[:token].present? }

  def index
    @user = current_user
    @all_venues = Venue.all.map { |v| { lat: v.latitude, lng: v.longitude } }
    @my_bookings = current_user.bookings
    @markers = @all_venues.filter { |v| !v[:lat].nil? }
    # raise
  end

  def show
    if params[:id]
      # Show booking like normal
      @booking = Booking.find(params[:id])
    else
      # Show booking with token
      @booking = Booking.find_by(token: params[:token])
    end

    # ORIGINAL SHOW METHOD
    # @booking = Booking.find(params[:id])

    @venue = @booking.venue
    @facts = @venue.cool_facts
    @venues = Venue.geocoded
    @all_venues = Venue.all.map { |v| { lat: v.latitude, lng: v.longitude } }
    @markers = @all_venues.filter { |v| !v[:lat].nil? }
    @my_place = [{ lat: @booking.latitude, lng: @booking.longitude }]

    # marker for map to display the venue location
     # @markers = [{
     #     lat: @venue.latitude,
     #     lng: @venue.longitude
     # }]
    @price = @venue.price
  end

  def new
    @booking = Booking.new
    @my_place = [{ lat: '-22.921797', lng: '-43.176173' }]
  end

  def create
    @booking = current_user.bookings.new(booking_params)

    if @booking.save
      # call the call_uber method to generate an uber request (Bookings model)

      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @booking.update(license_plate: booking_params[:license_plate],
                    status: booking_params[:status],
                    driver_name: booking_params[:driver_name],
                    price: booking_params[:price],
                    eta: booking_params[:eta],
                    pickup_time: booking_params[:pickup_time]
                  )
    redirect_to edit_booking_path(@booking)
  end

  def latest
    @bookings = Booking.all[0..10].reverse
  end

  def fetch_status
    @venue = @booking.venue
    @facts = @venue.cool_facts
    @venues = Venue.geocoded
    @markers = [{
        lat: @venue.latitude,
        lng: @venue.longitude
    }]
    @price = @venue.price
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:license_plate,
                                    :pickup_location,
                                    :passengers,
                                    :status,
                                    :driver_name,
                                    :price,
                                    :eta,
                                    :pickup_time,
                                    :latitude,
                                    :longitude,
                                    venue_types: [])
  end
end

app/views/bookings/_booking-show-link-modal.html.erb
<div class="modal fade" id="booking-show-link-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog" role="document">
     <div class="container col-9">

        <div class="modal-content" >

          <div class="modal-header" style="justify-content: center;">
              <h5 class="modal-title" id="exampleModalLabel" style="color:black;">Share with friends</h5>
          </div>

          <div class="modal-body col-12" style="color:black;">

            <div class="social-media" >
              <i class="fab fa-instagram"></i>
              <i class="fab fa-facebook-square"></i>
              <i class="fab fa-whatsapp-square"></i>
            </div>
            <!-- <input type="text" value="https://www.night-roulette.com/<%=@booking.token%>" id="myInput"> -->
          </div>
          <div class="modal-footer" style="color:black;">
            <button class="btn btn-dark col-12" id="share-btn" >Share</button>
          </div>
        </div>

     </div>
   </div>
</div>

app/views/bookings/_driver-confirmed.html.erb
<div class="container" id="driver-confirmed">
   <div class="row ct-section_header ct-section_header--type2"></div>
   <div class="row trip-details">
      <!-- <div class="venue-details col-9" style="background: url(<%#= image_url('bar1.jpg') %>;"> -->
      <h1 style="width: 300px;text-align: center;padding-bottom: 20px;"> Driver is en route 🙌  </h1></br>
      <div class="venue-details col-9">
        <div class="container">
          <div class="progress-bar">
            <div class="loaded-driver-confirmed">

            </div>
          </div>
        </div></br>
        <div>

          <p> Your driver is <%= @booking.driver_name %></p>
          <p>Driver ETA 🕛: <%= @booking.eta %></p>
          <p> Estimated 💸: <%= @booking.price %> </p>

          <p> License Plate 🚘: <%= @booking.license_plate %></p>
        </div>
      </br>
      <div style="display: flex;justify-content: center;">
          <img src="https://di-uploads-pod4.dealerinspire.com/olympiajeep/uploads/2018/03/Driving-Car.gif" width="219" >

      </div>



      </div>


     <!-- <button type="button" class="btn share-button" data-toggle="modal" data-target="#rating-modal">
         Rate this venue
      </button>
      <button type="button" class="btn share-button" data-toggle="modal" data-target="#booking-show-link-modal">
         Share venue with friends
      </button> -->

      <%# <div class="btn share-button">Share with your friends</div> %>
   </div>
</div>

app/views/bookings/_location-modal.html.erb
<div class="modal fade" id="location-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">

        <div class="modal-header">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div>
          <%= render 'map-confirmation' %>
        </div>

        <div id="geo-btn" style="btn btn-confirm-location" data-toggle="modal" data-target="#location-modal">Confirm location</div>

        </div>
        <div class="modal-footer">
        </div>
      </div>
   </div>
</div>

<% content_for(:after_js) do %>
  <script>
    document.getElementById("geo-btn").addEventListener("click", (event) => {
      document.getElementById("location-text").innerText = "Ladeira da Gloria 26"
    })
  </script>
<% end %>

app/views/bookings/_new-booking-form.html.erb
<%= simple_form_for booking do |f| %>
    <input type="hidden" name="booking[venue_types][]" />

    <fieldset class="form-group check_boxes optional booking_venue_types">
        <legend class="col-form-label pt-0">Customize which types:</legend>
        <div class="form-check">
            <input class="form-check-input check_boxes optional hidden" type="checkbox" value="bar" name="booking[venue_types][]" id="booking_venue_types_bar" style="display: none;">
            <label class="collection_check_boxes" data-for="booking_venue_types_bar">🍺 Bar</label>
        </div>
        <div class="form-check">
            <input class="form-check-input check_boxes optional hidden" type="checkbox" value="restaurant" name="booking[venue_types][]" id="booking_venue_types_restaurant" style="display: none;">
            <label class="collection_check_boxes" data-for="booking_venue_types_restaurant"> 🍽️ Restaurant</label>
        </div>
        <div class="form-check">
            <input class="form-check-input check_boxes optional hidden" type="checkbox" value="nightclub" name="booking[venue_types][]" id="booking_venue_types_nightclub" style="display: none;">
            <label class="collection_check_boxes" data-for="booking_venue_types_nightclub">🍸Club </label>
        </div>
    </fieldset>

    <%= f.input :latitude, label: false, class: 'hidden' %>
    <%= f.input :longitude, label: false, class: 'hidden' %>

    <div id="btn-location" style="btn btn-location" data-toggle="modal" data-target="#location-modal">Confirm location</div>

    <div>
        <p>Number of players</p>
    </div>

    <div class="row align-center">
        <div class="col-xs-2">
            <div class="plus" id="subtract-button"><i class="fas fa-minus"></i></div>
        </div>

        <div class="passengers-input col-xs-5" style="width: 30%;">
          <%= f.input :passengers, label: false, class: 'passenger-amount', input_html: {value: '1', disabled: true} %>
        </div>

        <div class="col-xs-2">
            <div class="plus" id="add-button"><i class="fas fa-plus"></i></div>
        </div>
    </div>

    <div class="bottom-navbar" style="align-items: center;">
        <div class="left-text">
            <p id="location-text">Undefined location</p>
            <p id="passenger-count">1 passenger</p>
        </div>
        <%= f.button :submit, "Place Bet 🃏", class: "btn btn-bottom-bar" %>
    </div>

<% end %>

app/views/bookings/_order-confirmed.html.erb
<div class="container" id="order-confirmed">
  <h1 style="margin: 20px auto 0 auto; text-align: center"> Ordering Taxi 🚘 </h1>
   <div class="row ct-section_header ct-section_header--type2"></div>
   <div class="row trip-details">
      <!-- <div class="venue-details col-9" style="background: url(<%#= image_url('bar1.jpg') %>;"> -->
      <div class="venue-details col-9">
        <div class="container">
          <div class="progress-bar">
            <div class="loaded-order-confirmed"></div>
          </div>
        </div>
        <div style="margin:10px auto 0 auto;">

          <p> We have selected a great <%= @venue.venue_type.capitalize %> and are now ordering you a taxi. It might take a few minutes so please hold tight! 🙊 </p> </br>

        </div>
        <div>
         <div class="star-rating" style="margin-top: 20px;">
          <%= render 'stars' %>
         </div>
         <div class="d-flex justify-content-between">
          <%= render 'pricing' %>
          <p style="margin-top: 10px;">Open until <%= @venue.hours %></p>
         </div>
        </div>
      </div>

      <%# <div class="btn share-button">Share with your friends</div> %>
   </div>

</div>

app/views/bookings/_pick-confirmed.html.erb
<div class="container" id="pick-confirmed">
  <h1 style="margin: 20px auto 0 auto; text-align: center"> Driver Arrived </h1>
   <div class="row ct-section_header ct-section_header--type2"></div>
   <div class="row trip-details">
      <!-- <div class="venue-details col-9" style="background: url(<%#= image_url('bar1.jpg') %>;"> -->
      <div class="venue-details col-9 mb-30" style="padding-top: 50px;">
        <div class="container">
          <div class="progress-bar">
            <div class="loaded-pick-confirmed"></div>
          </div>
        </div>

        <div><br/>
          <h5> You're going to </h5> <br/>
          <h2><%= @venue.name %>🎉 </h2><br/>
          <h5> Cool facts: </h5>
         <% @facts.each do |fact| %>
            <p><li> <%= fact %> </li></p>
         <% end %>
         </br>

        </div>
        <div>
         <div class=" star-rating">
          <%= render 'stars' %>
         </div>
         <div class="pricing-details">
            <%= render 'pricing' %>
         </div>
         <p class="hours">Open until <%= @venue.hours %></p>
        </div>
      </div>
        <div class="bottom-navbar d-flex justify-content-around" style="padding:0; background-color: black;">
          <div class="d-flex col-6">
            <button type="button" class="btn share-button-nav col-10 pick-confirmed-btn" data-toggle="modal" data-target="#booking-show-link-modal" style=" color: white; border:1px solid white;">
            Share
            </button>
          </div>
            <%# <div class="d-flex col-6">
              <button type="button" class="btn share-button-nav col-10 pick-confirmed-btn" data-toggle="modal" data-target="#rating-modal" style="color:black; background-color: white">
                 Rate
              </button>
            </div> %>

        </div>
   </div>
</div>

app/views/bookings/_pricing.html.erb
<div class="pricing-details">
    <% 5.times do |count|%>
        <% if @venue.price > (count + 1)%>
        <i class="fas fa-dollar-sign"></i>
        <% else %>
        <i class="fas fa-dollar-sign" style="opacity:.3;"></i>
        <% end %>
    <% end %>
</div>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/edit.html.erb
<div class="authentication-card">
  <%= simple_form_for @booking do |f| %>
    <%= f.input :license_plate %>
    <%= f.input :driver_name %>
    <%= f.input :price %>
    <%= f.input :eta %>
    <%= f.input :pickup_time %>
    <%= f.input :status, default: 'order-confirmed', collection: ['pending','order-confirmed', 'driver-confirmed', 'pick-confirmed', 'arrival-confirmed', 'not-rated', 'rated'] %>
    <%= f.submit %>
  <% end %>
  <%= link_to "Back", :latest_bookings %>
</div>

app/views/bookings/fetch_status.js.erb
var container = document.querySelector(".container");

<% if @booking.status == "pending" %>
  if (container.id != "pending") {
    document.querySelector(".add-margin-bottom").innerHTML = "<%= j render 'pending' %>";
  }
<% elsif @booking.status == "order-confirmed" %>
  if (container.id != "order-confirmed") {
    document.querySelector(".add-margin-bottom").innerHTML = "<%= j render 'order-confirmed' %>";
  }
<% elsif @booking.status == "driver-confirmed" %>
  if (container.id != "driver-confirmed") {
    document.querySelector(".add-margin-bottom").innerHTML = "<%= j render 'driver-confirmed' %>";
  }
<% elsif @booking.status == "pick-confirmed" %>
  if (container.id != "pick-confirmed") {
    document.querySelector(".add-margin-bottom").innerHTML = "<%= j render 'pick-confirmed' %>";
  }
<% elsif @booking.status == "arrival-confirmed" %>
if (container.id != "arrival-confirmed") {
  document.querySelector(".add-margin-bottom").innerHTML = "<%= j render 'arrival-confirmed' %>";
}
<% end %>

app/views/bookings/index.html.erb
<section class="hero venue-image" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://images.unsplash.com/photo-1556035511-3168381ea4d4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=967&q=80');">

   <h1><%= current_user.name %>'s Past Spins:</h1>
</section>
<section class="content">
  
  <button id="spin-it"> Click me</button>
  <%= render 'map' %>
  
   <section class="add-margin-bottom">
      <div class="container col-12">

  
        <div class="cards">

                <% current_user.bookings.each do |booking| %>
                  <!-- <div class="card_container"> -->
                    <div class="card_booking" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= booking.venue.picture %>);">
                      <div class="venue-name" style="text-align:center">
                        <%=booking.venue.name  %>
                      </div>

                      <div class="venue-type" style="text-align:center">
                         <% if booking.venue.venue_type == 'restaurant' %>
                            <div class="text-center"><i class="fas fa-utensils"></i></div>
                            <% elsif booking.venue.venue_type == 'bar' %>
                            <div class="text-center"><i class="fas fa-beer"></i></div>
                            <% elsif booking.venue.venue_type == 'nightclub' %>
                            <div class="text-center"><i class="fas fa-cocktail"></i></div>
                          <% end %>
                      </div>

                      <div class="link-back col-3" style="text-align:center">
                        <%= link_to "View Booking", booking, class: "btn btn-gradient" %>


                      </div>
                    </div>
                <% end %>
        </div>
   </section>
</section>

app/views/bookings/latest.html.erb
<section class="hero venue-image" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,1)), url('https://images.unsplash.com/photo-1556035511-3168381ea4d4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=967&q=80');">

   <h1><%= current_user.name.capitalize %>'s Past Spins:</h1>
</section>
<section class="content">
   <section class="add-margin-bottom">
      <div class="container col-12">
        <div class="cards">
            <% @bookings.each do |booking| %>
                <!-- <div class="card_container"> -->
                <div class="card_booking" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= booking.venue.picture %>);">
                    <div class="venue-name" style="text-align:center">
                    <%=booking.venue.name  %>
                    </div>

                    <div class="venue-type" style="text-align:center">
                        <% if booking.venue.venue_type == 'restaurant' %>
                        <div class="text-center"><i class="fas fa-utensils"></i></div>
                        <% elsif booking.venue.venue_type == 'bar' %>
                        <div class="text-center"><i class="fas fa-beer"></i></div>
                        <% elsif booking.venue.venue_type == 'nightclub' %>
                        <div class="text-center"><i class="fas fa-cocktail"></i></div>
                        <% end %>
                    </div>

                    <div class="link-back col-3 d-flex" style="text-align:center">
                        <%= link_to "Edit Booking", edit_booking_path(booking), class: "btn btn-gradient" %>
                        <%= link_to "View Booking", booking, class: "btn btn-gradient ml-3" %>
                    </div>
                </div>
            <% end %>
        </div>
   </section>
</section>

app/views/bookings/new.html.erb
<head>
  <script src="https://code.jquery.com/jquery-1.9.1.min.js">
  </script>
</head>
<div>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.dribbble.com/users/2172077/screenshots/7111433/media/3b65241a979a1ee3f4c15296ac30ee1a.gif) ;">
  </div>
    <h1 style="margin: 20px auto 0 auto; text-align: center"> Select </h1>
  <div class="booking-new">
    <div class="row" style="text-align: center;">
      <div class="header-text col-11" style="margin: 25px auto;">
        <div class="container">
          <div class="row">
            <div class="col-xs-12 col-sm-6 col-sm-offset-3">
              <div class="form-post">

                <%= render 'new-booking-form', booking: @booking %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
<%= render 'location-modal'  %>

app/views/bookings/show.html.erb
<section class="hero venue-image" style="background-image: linear-gradient(rgba(0,0,0,1),rgba(0,0,0,0)), url(<%= @venue.picture %>);">


</section>

<section class="content">
   <section class="add-margin-bottom">
      <% if @booking.status == 'pending' %>
        <%= render 'pending' %>
      <% elsif @booking.status == 'order-confirmed' %>
        <%= render 'order-confirmed' %>
      <% elsif @booking.status == 'driver-confirmed' %>
        <%= render 'driver-confirmed' %>
      <% elsif @booking.status == 'pick-confirmed' %>
        <%= render 'pick-confirmed' %>
      <% elsif @booking.status == 'arrival-confirmed' %>
        <%= render 'arrival-confirmed' %>
      <% end %>
   </section>
</section>


<%# Modal Closer to the body %>
<%= render 'booking-show-link-modal'  %>
<%= render 'venues/rating-modal', venue: @venue  %>
<%# It was beening rendered but not used anymore, since we have no more pending status %>
<%# <%= render 'car-order-modal', venue: @venue  %>

<%# Magic that updates every 3s %>
<%= link_to "I am invisible", fetch_status_booking_path(@booking.id), id: "invisible-twist", style: "display: none;", remote: true %>
<% content_for(:after_js) do %>
  <script>
    const interval = setInterval(function() {

     document.getElementById("invisible-twist").click();
    }, 3000);

  </script>
<% end %>