config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'venues#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :venues, only: [ :index, :show, :update]
  resources :bookings, except: [ :destroy ] do
    collection do
      get 'latest'
    end

    member do
      get 'fetch_status'
    end
  end

  get ':token', to: "bookings#show", token: /[A-Z]\d{5}/
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand navbar-light navbar-lewagon navbar-grid">
    <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "hamburguer-icon.png", class: "configs dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu nav-sidebar dropdown-menu-right nav-mobile mx-0" aria-labelledby="navbarDropdown">
            <%= link_to "Spin the wheel", new_booking_path, class: "nav-link" %>
            <%= link_to "Previous Spins", bookings_path, class: "nav-link" %>
            <%= link_to "Settings", edit_user_registration_path, class: "nav-link" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link nav-button" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link nav-button" %>
        </li>
      <% end %>
    </ul>
  </div>


</div>